declare var jqxBaseFramework: any;
//require('assets/js/jqxcore.js');
require('assets/js/jqxdata.js');
require('assets/js/jqxbuttons.js');
require('assets/js/jqxscrollbar.js');
require('assets/js/jqxlistbox.js');
require('assets/js/jqxdropdownlist.js');
require('assets/js/jqxmenu.js');
require('assets/js/jqxgrid.js');
require('assets/js/jqxgrid.filter.js');
require('assets/js/jqxgrid.sort.js');
require('assets/js/jqxgrid.selection.js');
require('assets/js/jqxpanel.js');
require('assets/js/jqxcalendar.js');
require('assets/js/jqxdatetimeinput.js');
require('assets/js/jqxcheckbox.js');
require('assets/js/globalization/globalize.js');